title: Qitas
subtitle: "锻造最美之器"
description: "锻造最美之器"
author: Qitas
timezone: PRC

url: https://www.qitas.cn
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy

highlight:
  enable: true
  line_number: false

weibo: qitas
linkedin: qitas
github: qitas/web
